language: dlang
script: dub build
before_install: 
- sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
- sudo apt-get update
- sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring 
- sudo apt-get update
- sudo apt-get install dub
- sudo apt-get install dmd-bin
deploy:
  provider: heroku
  app: firstd
  strategy: git 
  api_key: 
    secure: DCefRz801DTcXla9IAQwSGGkFVNtigMEvWPMSkNNELBjTY3RwaEOIxiDLAeNrZXDya/pd5glevQhl7WpyR1GIaLJCe0hfkrgmQF0ErKCr1SQ+kNFPTd6ltyeMevyA2Z5+tRnDmfXAd3mELuumd8QHBgojkR0Opl8ennzHAbgN4k=
#after_deploy:
# wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
#- heroku config:add rel=$(heroku releases | awk '{print $1$3$5$6}' | head -2 | tail -1)
